version: '2.4'

services:
  adminer:
    ports:
      - 8082:8080

  api:
    ports:
      - 8080:8080
    environment:
      APICORE_SERVER_URL: http://127.0.0.1:8080 # Url on which this service is available
      APICORE_SERVER_INTERFACE: http://localhost:8081 # Url on which admin is available

  admin:
    ports:
      - 8081:3000
    environment:
      REACT_APP_API_URL: http://127.0.0.1:8080 # Url on which is api available from outside
