version: 2
jobs:

  build:
    working_directory: /src
    docker:
      - image: docker:stable-git
    steps:
      - run:
          command: |
            docker build -t einstore/einstore-admin:${CIRCLE_SHA1} .
      - run:
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run:
          command: docker push einstore/einstore-admin:${CIRCLE_SHA1}
      - run:
         name: docker tag and push
         command: /src/.circleci/tag-and-push.sh ${CIRCLE_SHA1}

workflows:
  version: 2
  build-publish:
    jobs:

      - build:
          filters:
            tags:
              only: /.*/
