version: 2
jobs:

  build-branch:
    working_directory: /src
    docker:
      - image: docker:stable
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - checkout
      - run:
          command: |
            echo "export BRANCH_SLUG=\"$(echo ${CIRCLE_BRANCH} | sed -r s/[~\^]+//g | sed -r s/[^a-zA-Z0-9]+/-/g | sed -r s/^-+\|-+$//g | tr A-Z a-z)\"" >> $BASH_ENV
      - run:
          command: |
            docker build -t einstore/einstore-admin:${CIRCLE_SHA1} .
      - run:
          name: docker login
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run:
          command: |
            source $BASH_ENV
            docker tag einstore/einstore-admin:${CIRCLE_SHA1} einstore/einstore-admin:${BRANCH_SLUG}
            docker tag einstore/einstore-admin:${CIRCLE_SHA1} einstore/einstore-admin:${BRANCH_SLUG}_${CIRCLE_SHA1}
            docker push einstore/einstore-admin:${BRANCH_SLUG}
            docker push einstore/einstore-admin:${BRANCH_SLUG}_${CIRCLE_SHA1}


  build-tag:
    working_directory: /src
    docker:
      - image: docker:stable
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - checkout
      - run:
          command: docker build -t einstore/einstore-admin:${CIRCLE_TAG} .
      - run:
          name: docker login
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run:
          command: docker push einstore/einstore-admin:${CIRCLE_TAG}


workflows:
  version: 2
  test-build-publish:
    jobs:
      - build-branch
      - build-tag:
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/

