version: 2
jobs:

  build:
    working_directory: /src
    docker:
      - image: docker:stable
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - checkout
      - restore_cache:
          keys:
            - docker-build-v1
          paths:
            - /caches/app.tar
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /caches/.tar | true
      - run:
          command: |
            docker build --cache-from=einstore/einstore-admin -t einstore/einstore-admin:${CIRCLE_SHA1} .
      - run:
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run:
          command: docker push einstore/einstore-admin:${CIRCLE_SHA1}
      - run:
         name: docker tag and push
         command: /src/.circleci/tag-and-push.sh ${CIRCLE_SHA1}
      - run:
          name: Save Docker image layer cache
          command: |
            mkdir -p /caches
            docker save -o /caches/app.tar einstore/einstore-admin
      - save_cache:
          key: docker-build-v1
          paths:
            - /caches/app.tar

workflows:
  version: 2
  build-publish:
    jobs:

      - build:
          filters:
            tags:
              only: /.*/
